### ISSUE TITLE
Language of the COMMENTS decision making

### ISSUE THREAD

**Issue by Gluecksritter** [Gluecksritter/hello_world#1]

**Comment by julian1307** [comment]
Ich bin für Deutsch als "comment-Sprache" um Missverständnisse  vorzubeugen.

**Comment by Gluecksritter** [comment]
comprehensible, but English looks more professional

**Comment by julian1307** [comment]
Situativ stört das Übersetzen von Fachwörtern nur den work-flow ;)

**Comment by Gluecksritter** [comment]
Na dann eben Deutsch, um deinen ARBEITSFLUSS nicht zu stören!

**Comment by Gluecksritter** [comment]
:D

**Comment by julian1307** [comment]
Ich halte fest: wir wählen Deutsch als comment-Sprache.
