### ISSUE TITLE
README um Anleitung zum Start des Programms erweitern

### ISSUE THREAD

**Issue by julian1307** [Gluecksritter/hello_world#12]

**Comment by Gluecksritter** [comment]
Julian, ich würde sagen, das schreiben wir am Montag morgen zusammen?

**Comment by nipafx** [comment]
Dafür solltet ihr erstmal #13 gelöst haben - das könnt ihr aber gerne zusammen machen (wie alles andere natürlich auch).

**Comment by julian1307** [comment]
dieser issue kann mit dem merge von #29 ja geschlossen werden, und danach das release v1.0 erfolgen oder?!
