### ISSUE TITLE
Maven/Kotlin #13

### ISSUE THREAD

**Issue by Gluecksritter** [Gluecksritter/hello_world#13]
Hab es geschafft! Auch die pom.xml Datei ist erstellt! 
Probleme allerdings beim pushen! es kommt immer zu dem alten Pull request dazu, es entstehtalso  kein neues pull request, woran liegt dies? Irgendjemand eine ahnung?

**Comment by Gluecksritter** [comment]
also man kann es sehen bei #7 kleine Änderungen....

**Comment by Gluecksritter** [comment]
Problem gefunden! Ich hab den Gleichen Zweig benutzt um es zu pushen! 

@nicolaiparlog ist dies Problematisch? soll ich dies unter einem anderen Zweig nochmal pushen?

**Comment by nipafx** [comment]
Es sollte eine 1-zu-{0;1}-Beziehung zwischen Branches und Pull Requests geben, d.h. ihr erstellt einen Branch, arbeitet daran und erstellt irgendwann einen PR dazu. Den PR aktualisiert ihr (z.B. aufgrund meiner Anmerkungen), indem ihr den dazugehörigen Branch weiterbearbeitet (und pusht).

**Comment by Gluecksritter** [comment]
JAR Datei ist im neuen Pull Request nicht mehr da, wo liegt da der Fehler?

**Comment by nipafx** [comment]
Ins Repository gehören typischerweise keine Dateien, die aus anderen erzeugt werden können. Die JAR kann mit Maven aus dem Quellcode generiert werden - es gibt also keinen Grund sie extra rumzuschleppen. Deswegen schließt `.gitignore` sie auch aus.

**Comment by Gluecksritter** [comment]
Alles klar, das klingt logisch. 
Danke

**Comment by Gluecksritter** [comment]
@nicolaiparlog 
wenn ich das richtig sehe ist #15 ist damit bereit zum merge und dieses issue (#13) kann geschlossen werden.

Sodass nun #14 bearbeitet werden kann.
