### ISSUE TITLE
Travis?

### ISSUE THREAD

**Issue by Gluecksritter** [Gluecksritter/hello_world#14]
@nicolaiparlog 

Maven projekt ist erstellt #13 

Wie wird Travis jetzt genutzt?

**Comment by nipafx** [comment]
Ihr habt jetzt zwei Issues zur gleichen Aufgabe  (dieses und #10) - eines von beiden solltet ihr schließen.

Außerdem kann ich erst anfangen, wenn #13 erledigt ist.

**Comment by Gluecksritter** [comment]
#10 ist geschlossen und #13 erledigt

**Comment by nipafx** [comment]
@Gluecksritter muss Travis anschmeißen. Dazu bitte Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen. Ich konfiguriere Travis dann.

**Comment by Gluecksritter** [comment]
Schritt 2 war kein Problem, add .travis.yml ist mir noch ein rätsel.

**Comment by Gluecksritter** [comment]
ist #23 so ok ?
