### ISSUE TITLE
README leserlich machen

### ISSUE THREAD

**Issue by nipafx** [Gluecksritter/hello_world#19]
Die README ist aktuell sehr unleserlich. Dafür gibt es zweierlei Gründe:

* bei einigen Zwischenüberschriften fehlt das Leerzeichen nach `##`, weswegen GitHub sie nicht als Überschriften darstellt
* da in Markdown ein einfacher Absatz keine neue Zeile beginnt, ist die Projektbeschreibung eine unleserliche Mammutzeile

Letzteres ist vermutlich durch Copy-Paste aus dem OLAT entstanden. Um es zu lösen, müsst ihr die Aufzählungszeichen wieder einfügen. In Markdown geht das so:

```
* Level 1
    * Level 2
        * Level 3
```

* Level 1
    * Level 2
        * Level 3

**Comment by Gluecksritter** [comment]
habe die RREADME Datei den Änderungswünschen angepasst #20

**Comment by Gluecksritter** [comment]
die Fragezeichen sind drin geblieben! ich kümmere mich jetzt drum.

**Comment by Gluecksritter** [comment]
erledigt
