### ISSUE TITLE
Language of the CONVERSATION on GitHub decision making

### ISSUE THREAD

**Issue by Gluecksritter** [Gluecksritter/hello_world#2]

**Comment by Gluecksritter** [comment]
Dann sollten wir aus den selben Gründe auch hier Deutsch als Sprache wählen.

**Comment by julian1307** [comment]
das wollte ich auch gerade schreiben. ich bin also auch hier für Deutsch als Sprache!

**Comment by Gluecksritter** [comment]
Dann füge ich das in die Readme noch ein
