### ISSUE TITLE
Fehlermeldung beim Ausführen der .jar 

### ISSUE THREAD

**Issue by julian1307** [Gluecksritter/hello_world#27]
Wenn ich mit Maven einen clean install durchführe, erhalte ich beim ausführen in windows PowerShell (java -jar Datei.jar) folgende Fehlermeldung:
" kein Hauptmanifestattribut, in HalloTrain-1.0-SNAPSHOT.jar "
Ich denke da müsste Hello, World! erscheinen.
Wenn das behoben ist können wir die Anleitung #12 schreiben oder liege ich da falsch?

**Comment by nipafx** [comment]
Richtig, in der POM fehlt noch der Block für das Maven Assembly Plugin. Mit dem wird in der JAR die Hauptklasse festgelegt und alle benötigten Dependencies werden ebenfalls verpackt. Danach kann die Anleitung geschrieben werden.
