### ISSUE TITLE
Maven/Kotlin Projekt "Hello World" & JAR erstellen

### ISSUE THREAD

**Issue by julian1307** [Gluecksritter/hello_world#8]
Erstellen eines Maven/Kotlin Projekts das eine Klasse "HelloWorld.kt" mit der Main Methode print ausgeben kann. Zusätzlich soll eine JAR-Datei erstellt werden. 
de.thbingen.info2 soll als "group ID" verwendet werden und unser Gruppenname als "artifact id"

**Comment by Gluecksritter** [comment]
hat gedauert, aber hab es hinbekommen #13 
habe wie besprochen HelloTrain2  als Gruppenname für die artifact id benutzt.
Problematik beim Pushen wie in #13 beschrieben.
